$axure.loadCurrentPage({
  "url":"主页.html",
  "generationDate":new Date(1451027177526.26),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a8d247454f9d4776b18561b7c3eb7059",
    "type":"Axure:Page",
    "name":"主页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a53b06f426624bf2975dd52b64847680",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":80},
            "size":{
              "width":260,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"554150e58ebb48ddbde2c33e8b7c06be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":80},
                "size":{
                  "width":260,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u0.png"}},
{
          "id":"52737fd5800748e9aa633b969b5108ff",
          "label":"ModalPane",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":40,
              "y":115},
            "size":{
              "width":260,
              "height":369},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90e1ce2646954316b05767c6ff192048",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.3",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":40,
                  "y":115},
                "size":{
                  "width":260,
                  "height":369},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/modalpane_u2.png"}},
{
          "id":"2419fb0653f9414a824ff77aadd894f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":484},
            "size":{
              "width":260,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8672dd3b44674f2c8f5919fce72be990",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":484},
                "size":{
                  "width":260,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u0.png"}},
{
          "id":"4a8b3149d5464e34b5a51cbdc36084e1",
          "label":"0",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":80},
            "size":{
              "width":260,
              "height":105}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12f629671c3a468896044dcdef42fdde",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":80},
                "size":{
                  "width":260,
                  "height":105}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/0_u6.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "a53b06f426624bf2975dd52b64847680":{
      "scriptId":"u0"},
    "554150e58ebb48ddbde2c33e8b7c06be":{
      "scriptId":"u1"},
    "52737fd5800748e9aa633b969b5108ff":{
      "scriptId":"u2"},
    "90e1ce2646954316b05767c6ff192048":{
      "scriptId":"u3"},
    "2419fb0653f9414a824ff77aadd894f4":{
      "scriptId":"u4"},
    "8672dd3b44674f2c8f5919fce72be990":{
      "scriptId":"u5"},
    "4a8b3149d5464e34b5a51cbdc36084e1":{
      "scriptId":"u6"},
    "12f629671c3a468896044dcdef42fdde":{
      "scriptId":"u7"}}});